Scoring bug fix
witseie-elen4010/2024-group-lab-004 pull request #105
Opened 2024-05-14 08:23 UTC by samcohen1

There was a problem with the scoring, it has been fixed.

2024-05-14 10:29 UTC, RudolphTorlage commented on src/public/js/drawingBoard.js
> +    if (result.result.isImposter) {
Does this work in an elimination-style format? Or does the imposter win by not being voted in that one round?

2024-05-14 10:30 UTC, RudolphTorlage commented on src/server.js
> +        (isImposter && username !== room.imposterUsername && !twoMax)
What is the variable twoMax?

2024-05-14 10:30 UTC, RudolphTorlage requested changes
Please be more descriptive with variable names. Knowing what twoMax does is unclear.
Tests failed.

2024-05-14 16:22 UTC, samcohen1 commented on src/server.js
> +        (isImposter && username !== room.imposterUsername && !twoMax)
It is used when two people receive an equal number of votes. The variable name will be changed to make that clearer.

2024-05-14 16:22 UTC, samcohen1 commented on src/public/js/drawingBoard.js
> +    if (result.result.isImposter) {
The imposter wins by not being voted in that round. The eliminations can be a further recommendation for commercial release.

2024-05-14 18:15 UTC, BrentTB commented on src/public/js/drawingBoard.js
> +    if (result.result.isImposter) {
I believe an elimination would not be the best choice, as it would stop a user from interacting for a whole game, which can be quite long

2024-05-14 18:16 UTC, BrentTB commented on tests/drawingBoard.spec.js
the tests now load all three pages at once, instead of one at a time, which improves test speed, well done
the test also ensures the roomID has been generated before other pages use it, which is needed for when the tests are run faster than the webserver

2024-05-14 18:17 UTC, BrentTB approved these changes
The code is good, the fixed necessitated by @RudolphTorlage were added, the testing procedure was improved. Good job

2024-05-14 18:18 UTC, merged

2024-05-16 20:47 UTC, samcohen1 commented on src/server.js
> +        (isImposter && username !== room.imposterUsername && !twoMax)
The variable name has been changed to indicate what it does.