User story 20/admin role history
witseie-elen4010/2024-group-lab-004 pull request #108
Opened 2024-05-14 18:44 UTC by RudolphTorlage

Adds an admin role that has access to all games in the history tab
Admin role variables are secret
Temporary admin role has been created for testing purposes
Test included

closes #20

2024-05-14 18:50 UTC, BrentTB commented on src/controller/adminController.js
this requires an admin account set in the environment variable, it might be good to allow new admin's to be created, or for multiple admins to exist

2024-05-14 19:26 UTC, ChristopherPearse commented on src/controller/dbController.js
I assume this only allows for manual creation of administrative users? Is there a plan to incorporate the ability to create administrators inside the application? Or is it viewed as a case of administrators should only be able to be created by high-level members, thus only members with access to the DB?

2024-05-14 19:30 UTC, ChristopherPearse reviewed
At the time of this review, I saw the tests had originally failed and they are being rerun. The approval of this review is subject to change as a result of those tests. In the meantime, please address my concerns listed in the comments.

2024-05-14 19:30 UTC, ChristopherPearse commented on src/controller/dbController.js
I assume this only allows for manual creation of administrative users? Is there a plan to incorporate the ability to create administrators inside the application? Or is it viewed as a case of administrators should only be able to be created by high-level members, thus only members with access to the DB?

2024-05-14 19:30 UTC, ChristopherPearse commented on tests/admin.spec.js
The tests implemented during this phase pass satisfactorily.

2024-05-14 19:37 UTC, RudolphTorlage commented on src/controller/dbController.js
Yes, the plan is for only devs to be able to create admins. Creating them within the app opens up more security vulnerabilities, and is arguably more complex than manually adding them. We don't want to create millions of admins anyway.

2024-05-14 19:46 UTC, ChristopherPearse commented on src/controller/dbController.js
I 100% agree just wanted to confirm it was a factor that was taken into consideration. Thank you for addressing this promptly.

2024-05-14 19:59 UTC, ChristopherPearse requested changes
The tests appear to have failed, please amend this before approval.

2024-05-15 11:31 UTC, ChristopherPearse approved these changes
Tests passed.

2024-05-15 11:32 UTC, merged