Fixing disconnecting too early bug
witseie-elen4010/2024-group-lab-004 pull request #113
Opened 2024-05-14 21:07 UTC by samcohen1

Testing is problematic as sometimes it causes disconnection, this should fix that problem.

2024-05-14 21:27 UTC, ChristopherPearse requested changes

2024-05-14 21:27 UTC, ChristopherPearse commented on src/public/js/drawingBoard.js
This then causes issues if people disconnect while sending prompts. This should be implemented in such a way that people only get disconnected after they have been given a chance to load in, however, the game play must not be affected by a disconnect.

2024-05-15 06:36 UTC, samcohen1 commented on src/public/js/drawingBoard.js
It has been changed to beginning only once the game has started but includes before any prompts have been sent.

2024-05-15 08:59 UTC, merged

2024-05-16 20:48 UTC, samcohen1 commented on src/public/js/drawingBoard.js
This has further been altered to ensure its working is optimal. This improved both the functionality and the end-to-end testing.