User story 17/view past prompts
witseie-elen4010/2024-group-lab-004 pull request #70
Opened 2024-05-01 18:11 UTC by RudolphTorlage

The ability for users to view prompts from previous games has been added. Created a History button for users to access functionality. Guests will simply see an empty list. 
This also connects the application to an online database.
Basic Session Management has been implemented.

closes #17

2024-05-01 19:17 UTC, ChristopherPearse commented on src/controller/dbController.js
Are commented out sections to be added again later? If not please consider reducing clutter in the workspace.

2024-05-01 19:22 UTC, ChristopherPearse commented on tests/test-1.spec.ts
Satisfactory use of test cases, however please use the naming convention that was used throughout the rest of the project for test files.

2024-05-01 19:25 UTC, ChristopherPearse requested changes
Please address the concerns that I have illustrated through the comments. Overall the work was good however a  few formatting errors, as well as unit test errors.

2024-05-01 19:25 UTC, ChristopherPearse commented on tests/test-1.spec.ts
Subsequently the tests failed on various web browsers. Please amend before requesting to merge again.

2024-05-01 21:25 UTC, RudolphTorlage commented on src/controller/dbController.js
they will be added back in after all the other tests have been adjusted to go through the process of logging in to view certain pages

2024-05-01 21:26 UTC, RudolphTorlage commented
tests were failing due to secrets not being correctly added to github. This has been resolved.

2024-05-02 05:37 UTC, ChristopherPearse approved these changes
All issues from previous review have been resolved.

Code is of a good standard.

Test cases all pass.

2024-05-02 06:01 UTC, merged