User story 37/assigned normal player
witseie-elen4010/2024-group-lab-004 pull request #73
Opened 2024-05-07 20:50 UTC by BrentTB

When the game is started, the WebSocket stores how many users were in the room
When the room has that number of users again (ie: everyone has rejoined in the /draw page), an imposter is chosen
Each user receives a message saying imposter or normal
The prompt screen displays whether you are or are not the imposter
Exactly 1 imposter will be chosen, regardless of room size

closes #37

2024-05-08 06:14 UTC, RudolphTorlage commented on src/public/js/drawingBoard.js
> +socket.emit('joinGameRoom', roomId)
Improved variable clarity

2024-05-08 06:17 UTC, RudolphTorlage commented on src/public/js/drawingBoard.js
> +  console.log(playerStatus)
Remember to remove unnecessary console logs before requesting a merge.

2024-05-08 06:22 UTC, RudolphTorlage commented on src/server.js
> +      if (rooms[roomID].members.length === rooms[roomID].gameSize) {
Does this mean the imposter gets assigned as soon as the party is full? What if the imposter decides to leave the game, how does a new one get assigned? What if the host wants to start before the room is full? Maybe make it check whether an imposter has been assigned when the start button is clicked, and if not it can then do so?

2024-05-08 06:26 UTC, samcohen1 reviewed
The additions look good, Rudolph's requirements can be met and this can be implemented.

2024-05-08 06:30 UTC, RudolphTorlage requested changes
I left a comment discussing the  selection of the imposter:
https://github.com/witseie-elen4010/2024-group-lab-004/pull/73/files#r1593446383
Please remove console logs that are not necessary for functionality.
Test fails on waiting for function, I left a comment there too.
Improved naming of variables for clarity approved of.

2024-05-08 07:36 UTC, BrentTB commented on src/server.js
> +      if (rooms[roomID].members.length === rooms[roomID].gameSize) {
The imposter gets assigned once the party is full and the host presses the start game button (ie: when all players are in the /draw screen, not the /landing page)
If the imposter leaves the game, we will have to decide what to do, but it is a good idea to assign someone else

2024-05-08 08:54 UTC, merged

2024-05-15 21:16 UTC, BrentTB commented on tests/drawingBoard.spec.js
> +  await page3.waitForFunction(
I want to avoid a normal wait timer if possible, as the wait should be based on the webpage loading itself
A better solution appears to be the waitForSelector function, that waits until a certain selector exists