User story 18/see past drawings
witseie-elen4010/2024-group-lab-004 pull request #76
Opened 2024-05-09 00:37 UTC by BrentTB

Major updates to the database were made
a game session is saved every time a game starts
every drawing that is submitted is saved to the database
The history page now shows (unformatted) drawings from each game

2024-05-09 00:49 UTC, RudolphTorlage commented on src/app.js
> +app.use(bodyParser.json({ limit: '10mb' }))
I'm assuming this is because the image data is very large?

2024-05-09 00:51 UTC, RudolphTorlage commented on src/controller/dbController.js
> +const dbAccess = require('../db/dbAccess')
New database file? Why not add code in the dbController?

2024-05-09 00:52 UTC, RudolphTorlage commented on src/db/dbAccess.js
This could all go in the dbController

2024-05-09 00:53 UTC, RudolphTorlage commented on src/db/dbAccess.js
> +    game['gameName'] = 'some_default_game_name'
Should implement room name upon room creation

2024-05-09 00:55 UTC, RudolphTorlage commented on src/server.js
> +async function test() {
Does this code do anything?

2024-05-09 00:57 UTC, RudolphTorlage commented on src/server.js
> +    console.log('here:')
Please remove unnecessary console logs

2024-05-09 01:00 UTC, RudolphTorlage requested changes
Please remove code in server file that saves data to local computer.
Please remove dbAccess file and localise all code to dbController.

2024-05-09 01:09 UTC, RudolphTorlage approved these changes
Thank you for addressing the requested changes.

2024-05-09 01:09 UTC, merged

2024-05-15 21:13 UTC, BrentTB commented on src/controller/dbController.js
> +const dbAccess = require('../db/dbAccess')
This is a very good point, and must be fixed for consistency

2024-05-15 21:14 UTC, BrentTB commented on src/server.js
> +async function test() {
no, it was a sample for saving images sent over a socket, but it must be removed as it is not needed

2024-05-16 20:53 UTC, RudolphTorlage commented on src/controller/dbController.js
> +const dbAccess = require('../db/dbAccess')
thank you for fixing this.

2024-05-16 20:54 UTC, RudolphTorlage commented on src/db/dbAccess.js
> +    game['gameName'] = 'some_default_game_name'
This was implemented in a future update.